### ISSUE TITLE
Google Drive Folder for Weights File is Not Open Access

### ISSUE THREAD

**Issue by LostSputnik** [akdasUAF/ForestFireDetection#19]
Hi there, I ran into a snag while trying to follow the setup instructions from the README, particularly the part about downloading weight files from a Google Drive folder mentioned in the "How to install the code" section. It instructs to:

> Download the three files in [this Google Drive folder](https://drive.google.com/drive/folders/1aJDFIOFEKJhqdWJ3Ss87bVHyjHAvJaie?usp=sharing), including `yolov5.tar.gz` and `dataset.tar.gz`, and then move them into the repo directory for extraction.

However, when I attempt to access the folder, I'm prompted to request permission, suggesting it's not currently set for open access. Is this intentional, or should the folder be publicly accessible for download? Could you please look into this and adjust the access settings if needed? Thanks!

**Comment by LostSputnik** [comment]
I was able to set up the codebase and run the app without needing the weight files, as they are currently included. I'm keeping this issue to suggest a potential README update to reflect this. If needed, I'm eager to assist by contributing a PR.

**Comment by lbhnsh** [comment]
Hi, This may seem like a very stupid question but help is appreciated:
```
Traceback (most recent call last):
  File "/home/labhansh/ForestFireDetection/app.py", line 101, in <module>
    dbModel = DBN_import_model('Models/weights/dbn_1_RBM.joblib')
  File "/home/labhansh/ForestFireDetection/db_import_evaluate.py", line 13, in DBN_import_model
    loaded_pipeline = load(model_filename)
  File "/home/labhansh/.local/lib/python3.10/site-packages/joblib/numpy_pickle.py", line 658, in load
    obj = _unpickle(fobj, filename, mmap_mode)
  File "/home/labhansh/.local/lib/python3.10/site-packages/joblib/numpy_pickle.py", line 577, in _unpickle
    obj = unpickler.load()
  File "/usr/lib/python3.10/pickle.py", line 1213, in load
    dispatch[key[0]](self)
```
this is the error i get after running app.py and yes the drive link does require access, is the error due to same ?

**Comment by LostSputnik** [comment]
@lbhnsh not stupid at all! I don't think the error is due to the drive link as the necessary files are currently included. Can you please provide the full error so i can try to understand what's going wrong?

**Comment by lbhnsh** [comment]
T

> @lbhnsh not stupid at all! I don't think the error is due to the drive link as the necessary files are currently included. Can you please provide the full error so i can try to understand what's going wrong?

This is the full error. I presume the error is in joblib and then corresponding loading of models. I tried both pip installing requirements.txt and even independently pip installing joblib but doesn't seem to work. Quick question: Are you using GPU or CPU for this one?

**Comment by LostSputnik** [comment]
I'm using CPU for this one. I made a venv and pip installed using requirements.txt

**Comment by lbhnsh** [comment]
I'm using Python 3.10.12 and to my knowledge that shouldn't be a problem but the joblib is having the error.

**Comment by LostSputnik** [comment]
Closing after [this commit](https://github.com/akdasUAF/ForestFireDetection/commit/86c4e4b630e684e38cb9c8cba170d5421c394035) as the link is working now.
